### ISSUE TITLE
RuntimeError: parallel_for failed

### ISSUE THREAD

**Issue by BingEdison** [MohameHassan/prox#1]
Howdy! Really excited to try PROX but after installing all dependencies and datasets I've encountered an error when running the demo for fitting, any thoughts on what the cause could be?

Ubuntu 16.04
 File "/media/user/D4A13733C0473B76/Linux-Conda/anaconda3/envs/prox/lib/python3.6/site-packages/mesh_intersection-0.1.0-py3.6-linux-x86_64.egg/mesh_intersection/bvh_search_tree.py", line 39, in forward
    max_collisions=BVHFunction.max_collisions)
RuntimeError: parallel_for failed: invalid configuration argument

my terminal input can be found below 

python prox/main.py --config ~/prox/cfg_files/PROX.yaml --recording_dir ~/prox/prox_dataset/quantitative/recordings/vicon_03301_01  --output_folder ~/prox/PROX_results  --vposer_ckpt ~/prox/prox_dataset/models/vposer_v1_0/   --part_segm_fn ~/prox/prox_dataset/models/smplx_parts_segm.pkl   --model_folder ~/prox/prox_dataset/models

**Comment by mohamedhassanmus** [comment]
Hi Edison,
Thanks for your interest. Someone reported a similar issue when using conda. I would suggest creating a fresh virtual environment.

**Comment by BingEdison** [comment]
installing fresh virtual environment yields same error however when changing to torch 1.0.1.post2 completes more stages but halts on error. Is it the torch version I'm using ? any input appreciated.

OS:ubuntu 16.04 
gpu:nvidia 1080 

Camera initialization done after 2.1065
Camera initialization final loss 600.6396
Stage 000 done after 2.2657 seconds                                             
Stage 001 done after 6.1461 seconds                                             
Stage 002 done after 5.3607 seconds                                             
Orientation:   0%|                                        | 0/1 [00:13<?, ?it/sError inside sort: radix_sort: failed on 2nd step: invalid argument12,  4.01s/it]
Cuda failure src/bvh_cuda_op.cu:877: 'an illegal memory access was encountered'
(venv) user@user-Alienware-17-R3:~/prox$

**Comment by mohamedhassanmus** [comment]
Which torch version were you using before? `1.0.1.post2` is the right version
Your error is from the interpentration penalty. Did you build it and test it successfully as explained in https://github.com/vchoutas/torch-mesh-isect?
Another workaround if you just want to test PROX, is to turn it off. You can add this flag to your fitting command `--interpenetration False`

**Comment by BingEdison** [comment]
Success! what you've suggested worked .Rebuilding with torch1.0.1.post2 solved the issue ,  Setting to False worked solved before rebuilding. Many thanks for being so responsive, now PROX runs as described. Great work!!!

**Comment by sulei1998** [comment]
Hello! I meet the same question like you!

my error is :
Camera initialization done after 2.1234
Camera initialization final loss 600.6395
Stage 000 done after 2.2032 seconds                                             
Stage 001 done after 8.5100 seconds                                             
Stage 002 done after 7.5806 seconds                                             
Orientation:   0%|                                        | 0/1 [00:18<?, ?it/sError inside sort: radix_sort: failed on 2nd step: invalid argument15,  5.14s/it]
Cuda failure src/bvh_cuda_op.cu:877: 'an illegal memory access was encountered'

Could you tell me how can i solve the problem?  Now my pytorch version is 1.1.0. Should i must use the 1.0.1.post2?

**Comment by BingEdison** [comment]
Switching to torch 1.0.1post2 and rebuilding mesh intersect as suggested by
Hassan worked for me

**Comment by sulei1998** [comment]
But when you switch to the torch 1.0.1.post2, the human_body_prior needs the torch version>=1.1.  It make me confuse. Do you consider this problem? 

> 在 2019年12月6日，下午11:26，BingEdison <notifications@github.com> 写道：
> 
> ﻿Switching to torch 1.0.1post2 and rebuilding mesh intersect as suggested by
> Hassan worked for me
> 
>

**Comment by BingEdison** [comment]
I've experienced the same warnings above but demo is functioning despite
proceeding with torch 1.0.1 post2
