### ISSUE TITLE
Human mask in SMPL-X parameter fitting

### ISSUE THREAD

**Issue by cuiyuexin** [MohameHassan/prox#13]
Hello, nice work!

I have a question now. I found two masks in the PROX-Qualitative dataset, i.e. depth mask and RGB mask. I wonder which mask do you use in the (optional) E_D loss term in human fitting process. Are the masks calculated by yourself or provided by Kinect-One? When I visualize raw data by viz_raw_data.py, is the human point cloud segmentation the result of RGB mask or depth mask?

Thank you very much!

**Comment by mohamedhassanmus** [comment]
I use the RGB mask which is computed from Mask-RCNN. I found this to be more stable.

**Comment by cuiyuexin** [comment]
OK, I get it, thank you for your kindly help!
