### ISSUE TITLE
Cannot find normal files for the scanned scenes

### ISSUE THREAD

**Issue by sunshineatnoon** [MohameHassan/prox#14]
Hi, Thanks for releasing the code and datasets! 

Could you please tell me where I can find the normal files for the scanned scenes? Thanks!

**Comment by mohamedhassanmus** [comment]
Hi
The normals have a small effect from my experience and they are of huge size. To simplify the matter, I took them out from the penetration term equation. Please pull the recent changes and let me know if you face any other issue.

**Comment by sunshineatnoon** [comment]
Thanks so much for the clarification! I will check out the new code.
