### ISSUE TITLE
How to project human skeleton joints in the dataset to the world coordinate system?

### ISSUE THREAD

**Issue by sunshineatnoon** [MohameHassan/prox#15]
Hi, I've downloaded the human skeleton data from the website and visualized the joints in the 3D scene mesh. But it seems that the human joints coordinates are not aligned to the world coordinate system as shown below, could you please tell me if it's possible to project the joints to world coordinate?

![](https://raw.githubusercontent.com/sunshineatnoon/sunshineatnoon.github.io/master/images/Screenshot%20from%202020-09-23%2011-17-33.png)

**Comment by ZZWENG** [comment]
Here is the line that does that. `https://github.com/MohameHassan/prox/blob/master/prox/viz/viz_fitting.py#L81`

**Comment by sunshineatnoon** [comment]
> Here is the line that does that. `https://github.com/MohameHassan/prox/blob/master/prox/viz/viz_fitting.py#L81`

Thanks! This camera seems only fit for the SMPL model but not for the skeleton. I ended up extracting joints  from the SMPL fittings.

**Comment by mohamedhassanmus** [comment]
If I remember correctly, the raw Kinect skeleton is in the IR camera coordinates. I transform everything to the color camera coordinates first and then transform it to the world coordinates.

So to use the give camera2world transformation, you would need to transform the skeleton to the color camera coordinates first. You can check how I did it for the body scan here
https://github.com/MohameHassan/prox/blob/cf2c5f84e87a7d4a17621cfe71d855cfbcf31656/prox/projection_utils.py#L86

**Comment by ZZWENG** [comment]
> > Here is the line that does that. `https://github.com/MohameHassan/prox/blob/master/prox/viz/viz_fitting.py#L81`
> 
> Thanks! This camera seems only fit for the SMPL model but not for the skeleton. I ended up extracting joints from the SMPL fittings.

Hi @sunshineatnoon , may I ask how you extracted joints from the SMPL fittings? Is there a function that lets you extract the joints from the mosh meshes? (.ply file)

**Comment by sunshineatnoon** [comment]
> > > Here is the line that does that. `https://github.com/MohameHassan/prox/blob/master/prox/viz/viz_fitting.py#L81`
> > 
> > 
> > Thanks! This camera seems only fit for the SMPL model but not for the skeleton. I ended up extracting joints from the SMPL fittings.
> 
> Hi @sunshineatnoon , may I ask how you extracted joints from the SMPL fittings? Is there a function that lets you extract the joints from the mosh meshes? (.ply file)

You can recover SMPL first and get the joints from the recovered SMPL parameters.
