### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by sulei1998** [MohameHassan/prox#3]
Hello! Sorry to bother you! But when i run the demo for fitting, i have some problems. Could you give me some suggestions? 

**Here is my error**
Ubutu16.04
 File "prox/main.py", line 308, in <module>
    main(**args)
  File "prox/main.py", line 298, in main
    **args)
  File "/root/Workspace/prox_new/prox/fit_single_frame.py", line 405, in fit_single_frame
    focal_length=focal_length_x, dtype=dtype)
  File "/root/anaconda3/envs/sl/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/root/Workspace/prox_new/prox/fitting.py", line 76, in guess_init
    pose_embedding, output_type='aa').view(1, -1) if use_vposer else None
  File "/root/Workspace/prox_dataset/vposer_v1_0/vposer_smpl.py", line 114, in decode
    if output_type == 'aa': return VPoser.matrot2aa(Xout)
  File "/root/Workspace/prox_dataset/vposer_v1_0/vposer_smpl.py", line 152, in matrot2aa
    pose = tgm.rotation_matrix_to_angle_axis(homogen_matrot).view(batch_size, 1, -1, 3).contiguous()
  File "/root/anaconda3/envs/sl/lib/python3.6/site-packages/torchgeometry/core/conversions.py", line 233, in rotation_matrix_to_angle_axis
    quaternion = rotation_matrix_to_quaternion(rotation_matrix)
  File "/root/anaconda3/envs/sl/lib/python3.6/site-packages/torchgeometry/core/conversions.py", line 302, in rotation_matrix_to_quaternion
    mask_c1 = mask_d2 * (1 - mask_d0_d1)
  File "/root/anaconda3/envs/sl/lib/python3.6/site-packages/torch/tensor.py", line 362, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
Segmentation fault (core dumped)

**my terminal inputs are:**
python prox/main.py --config cfg_files/PROX.yaml --recording_dir /root/Workspace/prox_dataset/quantitative/recordings/vicon_03301_01 --output_folder  /root/Workspace/PROX_results --vposer_ckpt /root/Workspace/prox_dataset/vposer_v1_0/ --part_segm_fn /root/Workspace/prox_dataset/models/smplx_parts_segm.pkl --model_folder /root/Workspace/prox_dataset/models

**The main packages of my environment:**
python 3.6.3
pytorch 1.3.1
cuda 10.0

**Comment by mohamedhassanmus** [comment]
please downgrade your PyTorch version to `1.0.1.post2`

**Comment by sulei1998** [comment]
Hello! Thanks for your suggestion! But when i downgrade my pytorch version to 1.0.1.post 2, i find that i cann't import chamfer. So i decided to recreate a new environment. In this enviroment, I first download torch==1.0.1.post2, and then i open the file named ChamferDistancePytorch and run the code: python setup.py install.  Then i find i still cann't import chamfer.  

**here are my error:**
ImportError: /root/Workspace/ChamferDistancePytorch-719b0f1ca5ba370616cb837c03ab88d9a88173ff/chamfer.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

But when i use torch==1.3.1, i can import chamfer. It make me confuse. 

Another thing, when i follow the requirements.txt  to install packeages. I find that when i install the  _human_boday_prior_,  it will reminds me that :

_ERROR: human-body-prior 0.8.5.0 has requirement torch>=1.1.0, but you'll have torch 1.0.1.post2 which is incompatible._

But in your minds, i should use torch==1.0.1.post2. Could you tell me your version of human_body_prior?

I really want to know the steps of creating the envrioment.

**Comment by GYTuuT** [comment]
I have the some problem, when I install the environment by _pip install requirements.txt_, it comes the error too:

> ERROR: human-body-prior 0.8.5.0 has requirement torch>=1.1.0, but you'll have torch 1.0.1.post2 which is incompatible

Should I install an lower version of the package named  _human-body-prior_?

**Comment by mohamedhassanmus** [comment]
Probably your build didn't successed and your code is still calling the old build with the previous PyTorch version 1.3.1. Please delete your local copy of the chamfer distance and re-clone it, and then re-install with Pytorch `1.0.1.post2`.
PyTorch 1.1.0 should also work, anything >=1.2 won't work due to breaking changes https://github.com/pytorch/pytorch/releases/tag/v1.2.0.

**Comment by sulei1998** [comment]
Thanks for your suggestion! But now i meet the new error.

Here is my error:
Processing: /root/Workspace/prox_dataset/quantitative/recordings/vicon_03301_01/Color/s001_frame_00001__00.00.00.023.jpg
Found Trained Model: /root/Workspace/prox_dataset/vposer_v1_0/snapshots/TR00_E096.pt
/root/anaconda3/envs/sl2/lib/python3.6/site-packages/smplx/body_models.py:305: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  param[:] = torch.tensor(params_dict[param_name])
Camera initialization done after 2.4118
Camera initialization final loss 600.6395
Stage 000 done after 2.2808 seconds                                             
Stage 001 done after 3.8010 seconds                                             
Stage 002 done after 7.9781 seconds                                             
Orientation:   0%|                                        | 0/1 [00:14<?, ?it/sSegmentation fault (core dumped)                   | 3/6 [00:14<00:12,  4.31s/it]

This problem is caused by mesh-intersection?  Now my torch version is 1.0.1.post2. I uninstall my pytorch==1.1.0. Should i use pytorch==1.1.0?

**Comment by sulei1998** [comment]
Thank you for your suggestion! Now i can run the code!
I suggest the one who want to rebuild this project that you should create your virtual envirment with python, not conda!

**Comment by ZZWENG** [comment]
> Thank you for your suggestion! Now i can run the code!
> I suggest the one who want to rebuild this project that you should create your virtual envirment with python, not conda!

Hi @sulei1998, did you do anything specifically to get it to work besides creating a clean virtual env? I ran into the same segmentation fault as you did, but I am not able to fix it. Thanks!

**Comment by sulei1998** [comment]
> > Thank you for your suggestion! Now i can run the code!
> > I suggest the one who want to rebuild this project that you should create your virtual envirment with python, not conda!
> 
> Hi @sulei1998, did you do anything specifically to get it to work besides creating a clean virtual env? I ran into the same segmentation fault as you did, but I am not able to fix it. Thanks!

emm, i use ubuntu18.04, my installation process are:
- step 1
install cuda10.0 and cudnn 7.3
- step 2
create a env (use python3-venv)
- step 3
cd prox
pip install requirements
- step 4
cd mesh-master
follow the instruction
**maybe you need**
```sh
sudo apt-get install -y libsm6 libxext6 libxrender-dev
sudo apt-get install python3 python-dev python3-dev
sudo apt-get install libboost-dev
```
- step 5
cd chamfer
follow the instruction
- step 6
cd torch-mesh-isect-master
follow the instruction
**maybe you need**
```sh
cp /usr/local/cuda-10.0/samples/common/inc/helper_math.h /root/Workspace/send/torch-mesh-isect-master/include
apt-get install python-opengl
```

**Comment by ZZWENG** [comment]
> > > Thank you for your suggestion! Now i can run the code!
> > > I suggest the one who want to rebuild this project that you should create your virtual envirment with python, not conda!
> > 
> > 
> > Hi @sulei1998, did you do anything specifically to get it to work besides creating a clean virtual env? I ran into the same segmentation fault as you did, but I am not able to fix it. Thanks!
> 
> emm, i use ubuntu18.04, my installation process are:
> 
> * step 1
>   install cuda10.0 and cudnn 7.3
> * step 2
>   create a env (use python3-venv)
> * step 3
>   cd prox
>   pip install requirements
> * step 4
>   cd mesh-master
>   follow the instruction
>   **maybe you need**
> 
> ```shell
> sudo apt-get install -y libsm6 libxext6 libxrender-dev
> sudo apt-get install python3 python-dev python3-dev
> sudo apt-get install libboost-dev
> ```
> 
> * step 5
>   cd chamfer
>   follow the instruction
> * step 6
>   cd torch-mesh-isect-master
>   follow the instruction
>   **maybe you need**
> 
> ```shell
> cp /usr/local/cuda-10.0/samples/common/inc/helper_math.h /root/Workspace/send/torch-mesh-isect-master/include
> apt-get install python-opengl
> ```

Thank you so much! I will try this

**Comment by pgrady3** [comment]
I've gotten it to work with Conda. It took a bit of wrestling, but the following things helped:

- I used Pytorch 1.0.1.post2. You have to fiddle with human-body-prior and remove its dependence on Pytorch 1.1.0, but the rest installs fine
- Install the python packages with `python setup.py install` rather than `pip install -e .`. I thought these were identical, turns out they're not.
