### ISSUE TITLE
how to train 

### ISSUE THREAD

**Issue by GYTuuT** [MohameHassan/prox#4]
Hi, i have rebuilt the project and it worked well and the results is pretty great !
But now, I want  to train this model based on my  own dataset.  What should i do to make it? or just replace the paths of dataset?

**Comment by mohamedhassanmus** [comment]
This method is an optimization based method, so there is no training involved.
If you want to run it on your dataset, you would need to change the followings:

- camera calibration (what are you camera intrinsic)
- cam2world alignment
- sign distance field of your scene meshes

**Comment by GYTuuT** [comment]
Got it, Thanks !
