### ISSUE TITLE
keypoints.json

### ISSUE THREAD

**Issue by sulei1998** [MohameHassan/prox#5]
Hello! I am very excited to run the demo for fitting! Now I can run the demo in the Quantitative PROX dataset. But when i want to run the demo in the Qualitative PROX dataset, i find that i don't have the keypoints.json. I visit the website, but i still can't find it. Could you tell me where i can find these files. Maybe you have forgotten to upload these files?

**Comment by mohamedhassanmus** [comment]
The keypoints for the qualitative data are not provided currently. You can get them by running openpose or any other 2d pose estimator. We also provided the final fitting results as part of the downloads if that is what you need.

**Comment by sulei1998** [comment]
Thank you for your  work! I would appreciate it if you could upload the final fitting results! Hope you have a nice day!
