### ISSUE TITLE
 No such file or directory: N3OpenArea_normals.npy

### ISSUE THREAD

**Issue by sulei1998** [MohameHassan/prox#7]
Hello! Sorry to bother you. But when i want to run the demo in the prox-internal_vposer. I got the error: **No such file or directory: '/root/Workspace/prox_dataset/qualitative/sdf/N3OpenArea_normals.npy'**. Then I re-download the sdf file again. But I still can not find the file. Maybe you have not upload the file? 
Hope you have a happy christmas！

**Comment by wkailiu** [comment]
@sulei1998 I have the same problem. How did you solve this problem?

**Comment by sulei1998** [comment]
> @sulei1998 I have the same problem. How did you solve this problem?
Emm, I don't find the file.
