### ISSUE TITLE
Can you render/fit while logged in via SSH

### ISSUE THREAD

**Issue by wangzheallen** [MohameHassan/prox#8]
"ValueError: Failed to initialize Pyglet window with an OpenGL >= 3+ context. If you're logged in via SSH, ensure that you're running your script with vglrun (i.e. VirtualGL). The internal error message was "Could not create GL context""

When I used  server. Seems the error comes with
"r = pyrender.OffscreenRenderer(viewport_width=W,
                                       viewport_height=H,
                                       point_size=1.0)"

from fit_single_frame.py line 707.

**Comment by mohamedhassanmus** [comment]
Try this 
```
import os
os.environ['PYOPENGL_PLATFORM'] = 'egl'
os.environ['EGL_DEVICE_ID'] = os.environ['GPU_DEVICE_ORDINAL'].split(',')[0]
import pyrender
```

**Comment by wangzheallen** [comment]
> os.environ

Thanks for your reply!
I guess the "os.environ['GPU_DEVICE_ORDINAL'].split(',')[0]" is '0'?, seems it is your pre-defined environment variable.
I tried to replace "os.environ['GPU_DEVICE_ORDINAL'].split(',')[0]" with '0', however, get
"OpenGL.GL.shaders.ShaderValidationError: Validation failure (0): "

**Comment by mohamedhassanmus** [comment]
The above fix works for me but this is an issue with Pyrender. So maybe you need to write a small code to test that, and also check pyrender github page. I see few similar issues

**Comment by wangzheallen** [comment]
Thanks for your answer, could you please help print out your 'os.environ['GPU_DEVICE_ORDINAL']'
I looked into the pyrender github and followed the instruction, however, not solving my problems.

**Comment by wangzheallen** [comment]
Solved by upgrading system.

**Comment by sulei1998** [comment]
> Solved by upgrading system.

hello, I met the same problem. Can you tell me how you solved it？You are using ubuntu20.04?
