### ISSUE TITLE
What loss does "--interpenetration False" disables?

### ISSUE THREAD

**Issue by wangzheallen** [MohameHassan/prox#9]
in https://github.com/vchoutas/smplify-x/issues/9
and https://github.com/vchoutas/smplify-x/issues/3
They can disable the interpenetration loss, as they are for general smplify.
However, in PROX, if the interpenetration is disabled, what loss will be disabled?
Now in PROX.yaml, we have
flip: True
contact: True
sdf_penetration: True
use_joints_conf: True
use_pca: True
use_hands: True
use_face: True
flat_hand_mean: False
interpenetration: True
penalize_outside: True
interactive: True
visualize: False
use_vposer: True

and loss function is in https://github.com/MohameHassan/prox/blob/master/prox/fitting.py#L627
with joint_loss + pprior_loss + shape_loss +
                      angle_prior_loss + pen_loss +
                      jaw_prior_loss + expression_loss +
                      left_hand_prior_loss + right_hand_prior_loss + m2s_dist + s2m_dist
                      + sdf_penetration_loss + contact_loss

Which one is going to be disabled?
Thanks!

**Comment by mohamedhassanmus** [comment]
The flag has the same behavior as in SMPLify code

**Comment by wangzheallen** [comment]
> The flag has the same behavior as in SMPLify code

Thanks for the answer! is that possible to tell the difference or give the hint (github pape or weblink) between SMPlify and prox?

Does that mean, with the flag 'interpenetration' as False, the sdf_penetration_loss,  and self-penetration term will be disabled?

Thanks!

**Comment by wangzheallen** [comment]
Solved by upgrading system.
